version: 2
jobs:
  validate:
    resource_class: medium+
    docker:
      - image: circleci/node:7.10.0-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test-coverage
          command: npm run test-coverage
      - store_artifacts:
          path: coverage
          prefix: coverage

  compile:
    resource_class: medium+
    docker:
      - image: circleci/node:7.10.0-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: lint
          command: npm run lint
      - run:
          no_output_timeout: "20m"
          name: build
          command: |
            if [ "${CIRCLE_BRANCH}" == "mock" ]; then
              npm run build -- -env=mock
            elif [ "${CIRCLE_BRANCH}" == "master" ]; then
              npm run build -- -env=prod
            else
              npm run build -- -env=qa
            fi

workflows:
  version: 2
  build:
    jobs:
      - validate
      - compile
