export class Constants {

   public static labels = {
      openAccount: {
         accept: 'Accept',
         closeBtnText: 'Close',
         backToOverview: 'Back to overview',
         apply: 'Apply',
         initialDeposit: 'Initial deposit',
         additionalDeposit: 'Additional deposit',
         access: 'Access',
         yes: 'Yes',
         no: 'No',
         depositType: 'deposit-type',
         afterOneDay: 'After 24 hours\' notice',
         afterThirtyTwoDays: 'After 32 days\' notice',
         endInvestment: 'At the end of my investment period',
         twentyFourHour: '24h',
         thirtyTwoDay: '32d',
         noticeDeposit: 'Y',
         depositAmount: 'How much would you like to deposit?',
         makeDeposit: 'Would you want to make more deposits once the account is open?',
         accessMoney: 'How soon would you want to access your money?',
         initialAmount: 'Initial deposit amount',
         amountErrorMessage: 'Amount should be equal to or greater than ',
         minimumAmount: 'Please enter an amount of at least ',
         seeAllProducts: 'See all products',
         nextBtn: 'Next',
         interestRate: 'your interest rate is ',
         upTo: 'up to',
         interestPerAnnum: '% p.a.',
         openAccountBtn: 'Open account',
         seeOtherProductBtn: 'See other investment products',
         seeLessBtn: 'See less',
         investments: 'Investments',
         clickHere: 'click here.',
         goToOverview: 'Done',
         back: 'Back',
         edit: 'Edit',
         selectDay: 'Enter a day of the month between 1 and 31.',
         depositEachTime: 'How much would you like to deposit each time?',
         receiveInterest: 'Your first recurring payment will be on ',
         paymentMade: ' From which account will the payment be made?',
         chooseDay: 'Choose a day',
         chooseAccount: 'Choose an account',
         interestDuration: 'How often do you want your interest paid out?',
         payInterest: 'Into which account should we pay your interest?',
         receiveInterestDay: 'On which day do you want to receive your interest?',
         next: 'Next',
         seeAllInvestment: 'See all investment products',
         chooseOptions: 'Choose an option',
         selectAccount: 'Select an account',
         investorNumber: 'Choose investor number',
         selectInvestorNumber: 'Which investor number do you want to use?',
         payDepositAccount: 'From which account will you pay the deposit?',
         insufficientFund: 'There\'s not enough money in the account you chose. Please choose another.',
         monthDetails: 'How many months do you want to invest for?',
         monthRange: 'Enter the number of months between',
         recurringAmount: 'Minimum amount of ',
         initialdeposit: 'initialdeposit',
         interestPayout: 'interestpayout',
         time: 'T',
         tryAgain: 'Try Again'
      },
   };

   public static messages = {
      openNewAccount: {
         investmentAccount: 'Open a new investment account',
         newAccount: 'Opening a new account should take you about 5 minutes.',
         allInfo: 'All information is required, unless marked as optional.',
         letsStart: 'Let\'s get started',
         acknowledge: 'You confirm and acknowledge that you\'ve read, understood and accept the ',
         financialAdvisor: 'Financial Advisory and Intermediary Services(FAIS) Act',
         disclosure: 'disclosures for this product.',
         agreeMessage: 'You confirm that you’ve chosen this account out of your own free choice and \
         that if you don’t understand anything, or if you need advice or help choosing an account, you\’ll\
          call 0860 555 111 or visit a Nedbank branch before opening an account.',
         disclaimerAbove: 'disclaimer above.',
         end: 'end',
         moneyPeriod: 'money-period',
         form1: 'IOform1',
         form2: 'IOform2',
         form3: 'IOform3',
         depositFlag: 'depositFlag',
         keepDepositFlag: 'keepDepositFlag',
         accessMoneyFlag: 'accessMoneyFlag',
         noticePeriod: 'Notice Period',
         option1: 'Option1',
         option2: 'Option2',
         option3: 'Option3',
         ourInvestmentHeader: 'OUR INVESTMENT PRODUCTS',
         suggestionHeader: 'OUR SUGGESTIONS',
         noProducts: 'No Products found matching your specified filter criteria',
         goodOptionSubHeader: 'BASED ON YOUR NEEDS, THESE ACCOUNTS ARE GOOD OPTIONS FOR YOU.',
         openAccountHeader: 'Open a new investment account',
         chooseOption: 'Let\'s find the right option for you',
         filterBy: 'Filter by',
         noteHeader: 'Please note',
         interestMessage: 'Your choice affects your interest rate. Choosing to access your\
          money during the investment period may lower your interest rate.',
         contentWrapper: 'content-wrapper',
         seeAllInvestment: 'See all investment products',
         amountShouldGreaterMessage: 'Amount should be equal to or less than 99 999 999.99',
         taxFreeSavingsAccountMsg: 'The maximum annual limit for a Tax Free Savings Account is R33 000',
         nonFica: 'You’re currently not FICA compliant',
         visitFica: 'Please visit a branch with your ID and proof of residence, or call 0860 555 111 for help.',
         steps: ['Product', 'Account details', 'Review'],
         depositDetails: 'Deposit details',
         interestDetails: 'Interest details',
         recurringPayment: 'Recurring payment',
         openAccountTitle: 'Your new investment account has been opened.',
         success: 'You\'re done!',
         investmentAcc: 'Investment account',
         note: 'Things you need to know:',
         businessMessage: 'Your account may take up to 2 business days to show. For more information on our processing times,',
         manageAccountMessage: 'You can manage your account from the Investments account overview page.',
         contactUs: 'Contact us',
         almostDone: 'You’re almost done!',
         allInformationMessage: 'Please check that all the information is correct before we open your investment account.',
         accountDetails: 'Account details',
         accountType: 'Account type',
         openDeposit: 'Opening deposit',
         fromAccount: 'From account',
         investmentPeriod: 'Investment period',
         interestPayout: 'Interest payout',
         interestRate: 'Your interest rate is ',
         validRate: 'This rate is only valid if you',
         openYourAccount: 'open your account today.',
         payOutOption: 'Payout option',
         payOutDate: 'Payout day',
         payOutAccount: 'Payout account',
         frequency: 'Frequency',
         day: 'Day',
         amount: 'Amount',
         legalStuff: 'The legal stuff',
         confirmMessage: ' You confirm that you\'ve read and agreed to the',
         termsAndCondition: 'terms and conditions.',
         regularPayment: 'Add a recurring payment',
         recurringPayments: 'Do you want to make recurring payments into your new account?',
         recurringSubHeader: 'We’ll set up a recurring payment from your Nedbank account into your new investment account.',
         recurringMessage: 'If you change your mind later, you can add a recurring payment after your account is open.',
         paymentsHappen: 'How often should the payments happen?',
         recurringPaymentDay: 'On which day should the payment happen?',
         paymentDuration: 'payment-duration',
         yourAccount: 'Your account: ',
         interestValidToday: 'This interest rate is valid only if you open your investment account today.',
         moreMoney: 'The more money you save, the higher your interest rate could be.',
         previousInvestmentAccount: 'We created your investor number when you opened previous investment accounts.',
         linkAccount: 'We\'ll link your new investment account to your existing investor number.',
         investorNumbers: ' Your investor number is:',
         receiveInterestNote: 'You’ll receive your interest on',
         errorMessage: 'Apologies! Looks like something\'s wrong on our side.',
         aboutNetbankInvest: 'About Nedbank investments',
         openInvestmentProduct: 'You can open more than one investment product on the same day.',
         stopOrderInfo: 'If the due date of a stop order payment falls on a Sunday, the payment will only be processed on Monday.',
         internetBankingInfo: 'When we maintain our systems, certain internet banking functions may not be available.',
         processingTimes: 'Processing times for investment accounts ',
         investInfo: 'Investment instructions submitted',
         reflectTransc: 'When transaction will reflect',
         weekdaysBefore: 'Weekdays before 19:00',
         nextBusinessDay: 'The next business day',
         weekdaysAfter: 'Weekdays after 19:00',
         businessDay: 'In 2 business days',
         beforeSaturdays: 'Saturdays before 15:30',
         nextMonday: 'The next Monday',
         afterSaturday: 'Saturdays after 15:30, or Sundays',
         nextTuesday: 'The next Tuesday',
         beforeHoliday: 'Before 19:00, the day before a public holiday',
         afterNineteen: 'After 19:00, the day before a public holiday',
         withinTwoDay: 'Within 2 business days',
         investmentProductInfo: 'For more information on our investment products and to compare interest rates, please visit',
         logoutHeader: 'Going somewhere else?',
         logoutSubHeader: 'Going somewhere else?Your progress will be lost if you choose to leave this page.',
         cancelTransaction: 'Cancel this Transaction',
         stayOnThisPage: 'Stay on this page',
      }
   };

   public static variableValues = {
      openNewAccount: {
         clientType51: '51',
         clientType52: '52',
         currency: 'R',
         yes: 'Y',
         no: 'N',
         optionText2: 2,
         optionText3: 3,
         amountLimit: 99999999.99,
         taxFreeAmountLimit: 33000,
         TaxFreeAccountType: 49,
         empty: '',
         selectedProduct1: 1,
         weekly: 'Weekly',
         monthly: 'Monthly',
         monthlyPayment: 'M',
         weeklyPayment: 'W',
         weekDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
         investmentEnd: 'When my investment period ends',
         quarterly: 'Quarterly',
         halfYearly: 'Half-yearly',
         yearly: 'Yearly',
         months: 'months',
         year: 'A',
         quarter: 'Q',
         halfYear: 'H',
         endInvestment: 'E',
         contactNumber: '0860 555 111',
         minimumDeposit: 50,
         startDay: 1,
         endDay: 31,
         zeroProduct: 0,
         investmentType: 'This investment account',
         capitalizeAccount: 'CAP',
         two: '02',
         three: '03',
         successCode: 'R00',
         nedBankSite: 'https:\\www.nedbank.co.za',
         non: 'NON',
         percent: '%',
         four: 4
      }
   };

   public static symbols = {
      hyphen: ' - ',
      hyphenWithoutSpace: '-',
      withoutSpace: '',
      fullStop: '.'
   };

   public static routeUrls = {
      dashboard: '/dashboard'
   };

   public static amountPipeSettings = {
      amountWithPrefix: {
         hidePrefix: false,
         isLabel: true,
         showSign: false,
         noDecimal: false
      }
   };
   public static metadataKeys = {
      transaction: 'TRANSACTION'
   };
}
