export class CreditLimitMaintenance {
   public static labels = {
      limitIncrease: 'Request credit limit increase',
      creditFacility: 'Increase your credit facility hassle free',
      durationInfo: 'The application will take 5-10 minutes of your time',
      documentInfo: 'You’ll need to provide the following as per National Credit Act:',
      documentOne: 'Your Income and expense details.',
      documentTwo: 'Your latest 3 months payslips or 3 months bank statements to prove your income',
      applyAndAccept: 'In order to apply for credit limit increase, you must accept:',
      otherdocumentInfo: `If you don't have payslip or bank statement you can provide the following documents:`,
      finacialDetails: 'Financial details',
      specifyDetails: 'Specify your income and expenses details',
      income: 'Income',
      grossIncome: 'Gross monthly income',
      netIncome: 'Net monthly income',
      addOthersources: 'Income from other sources (optional)',
      otherSource: 'Total income from other sources',
      otherSourceOptional: 'Total income from other sources (optional)',
      expenses: 'Expenses',
      commitments: 'Monthly commitments',
      debt: 'Monthly debt',
      questionMark: '?',
      exclamationMark: '!',
      bankAccountDetails: 'Bank account details',
      retrievalConsent: 'Statement retrieval consent',
      specifyYourBank: 'Specify your bank account details where your income is deposited',
      bankName: 'Bank name',
      bankNameWithColon: 'Bank name:',
      account: 'Account',
      accountNumber: 'Account Number',
      accountNumberWithColon: 'Account Number:',
      contactNumber: 'Preferred contact number:',
      contactNumberWithoutColon: 'Preferred contact number',
      contactDetails: 'Contact details',
      contactStatus: 'Please check your contact details so one of our consultants can contact you to confirm any additional information.',
      summary: 'Summary',
      edit: 'Edit',
      mailTo: 'mailto: CardDocs@Nedbank.co.za?subject= Credit limit increase documents',
      body: '&body=',
      pleaseRemember: 'PS: Remember to add your ID number as a reference on your supporting document.',
      currentAccount: 'CA',
      debtReview: 'N'
   };
   public static messages = {
      declarationOnlyForMe: `I hereby agree that I am not under administration, undergoing debt counselling,
         have any dispute pending with the credit bureau, declared insolvent or under curatorship.`,
      declarationForMeAndSpouse: `I hereby agree that me and my spouse are not under administration, undergoing debt counselling,
         have any dispute pending with the credit bureau, declared insolvent or under curatorship.`,
      declarationForManual: `I understand that <b>I have 4 days to submit documents</b> or else the application will be cancelled.`,
      ifYouAre: 'If you are',
      selfEmployed: 'self-employed:',
      selfEmployedInfo: 'A letter from your accountant or your latest financial statements or an IT34.9',
      salaryEarner: 'a salary earner/commission earner and received a salary increase or promotion:',
      salaryEarnerInfo: 'A formal letter of employment reflecting income',
      contractWorker: 'a contract worker:',
      contractWorkerInfo: 'Proof of employment (signed contract), contract period in South Africa must not be less than 6 months',
      employed: 'employed for less than three months:',
      employedInfo: 'A formal letter of employment reflecting income',
      salaryEarnerReturn: 'a salary earner returning from long leave:',
      salaryEarnerReturnInfo: 'A formal letter of employment reflecting income',
      grossIncomeTip: 'Your average gross income over a 3 or 12 months period.',
      grossIncome: 'Gross monthly income:',
      netIncome: 'Net monthly income:',
      netIncomeTip: 'Your average net income over a 3 or 12 months period.',
      addOthersources: 'Income from other sources:',
      totalIncome: 'Total income from other sources:',
      addOthersourcesTip: `Other income includes: fringe benefits or allowances, commission or bonus, rental income,
      inheritance, maintenance received or dividends`,
      debt: 'Monthly debt:',
      debtTip: `Monthly debt may include, home loan installment, personal loan installment, installment loans,
         vehicle installments, credit card installment, store card installments, overdraft, maintenance paid or other debt repayments`,
      commitments: 'Monthly commitments:',
      commitmentsTip: `Monthly commitments may include, municipal rates & bills, rental accommodation, education fees, transport & fuel,
         groceries, food & clothing, insurances, savings & investments, cell phone, telephone, entertainment and other expenses`,
      retrieveStatement: 'Do you want us to retrieve your bank statement automatically?',
      bankList: '(An income supporting document can be retrieved from Nedbank, ABSA and Standard Bank)',
      summaryStatus: 'Please review the information for your credit card limit increase application',
      summaryDeclaration: `By submitting this application, I hereby declare that the information provided by me is
         correct and true to my knowledge and Nedbank can verify the provided information`,
      yesIaggree: 'Yes, I agree',
      noProvideManually: `No, I'll provide manually`,
      validKeys: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '0'],
      title: 'Contact person',
      backspace: 'Backspace',
      enterContactNumber: 'Please enter a contact number.',
      enterValidContactNumber: 'Please enter a valid contact number.',
      errorMessageForAmount: 'Please enter an amount.',
      errorMessageForGrossIncome: 'Gross monthly income should be greater than the Net monthly income.'
   };
   public static informations = {
      almostDone: 'You’re almost done',
      reviewing: 'We are reviewing your application.',
      almostDoneStatus: 'We’ve received your credit limit increase request, but still need your documents.',
      reviewingStatus: 'You will hear from us shortly with an outcome.',
      onlineApplication: 'Online application',
      onlineApplicationStatus: 'You’ve completed the online application.',
      submitDocuments: 'Submit documents',
      submitDocumentsStatus: 'Email or fax us your documents.',
      weContactYou: 'We contact you',
      weContactYouStatus: 'We will contact you via  SMS within 5 working days with the outcome of your application.',
      howToSend: 'How to send your documents',
      paySlips: 'We need your latest 3 months payslips or 3 months bank statements to prove your income  ',
      addIdNumber: 'Add your ID number as a reference on your supporting document.',
      mailSubject: `Mail subject line must be: 'Credit limit increase documents'.`,
      bodyOfMail: `Body of email must include: Your name, surname & ID.`,
      sendDocuments: 'Send documents by email to',
      emailId: 'CardDocs@Nedbank.co.za',
      orFax: 'or  Fax documents to',
      phoneNumber: '010 251 0312',
      contactUs: 'Contact us',
      tractStaus: 'To track the status of your application, please call us at',
      trackPhoneNumber: '0860 555 111',
      yourDone: 'You’re done',
      yourDoneStatus: 'We will review your application and you will hear from us within 5 working days with an outcome.',
      maritalStatus: [
         { value: 'D', text: 'Divorsed' },
         { value: 'K', text: 'Unknown' },
         { value: 'M', text: 'Married' },
         { value: 'S', text: 'Seperated' },
         { value: 'U', text: 'Unmarried' },
         { value: 'W', text: 'Widow' }
      ],
      marriageType: [
         { value: '01', text: 'MARRIED IN COMMUNITY OF PROPERTY' },
         { value: '02', text: 'MARRIED OUT OF COP WITHOUT ACCRUAL' },
         { value: '04', text: 'MARRIED OUT OF COP WITH ACCRUAL' },
         { value: '05', text: 'FOREIGN/ CUSTOMARY MARRIAGE' },
         { value: '20', text: 'TRIBAL MARRIAGE' }
      ],

   };
   public static steps = ['Income and expenses', 'Documents', 'Contact details', 'Summary'];
   public static banks = [{ bankName: 'Nedbank', branchNumber: '198765' },
   { bankName: 'ABSA', branchNumber: '632005' },
   { bankName: 'Standard Bank', branchNumber: '051001' }];
   public static tooltipValues = {
      income: [
         { isOpen: false, text: 'gross-income' },
         { isOpen: false, text: 'net-income' },
         { isOpen: false, text: 'other-income' },
         { isOpen: false, text: 'commitments' },
         { isOpen: false, text: 'debt' },
      ]
   };
   public static routerUrls = {
      success: 'dashboard/account/credit/limit/success/',
      review: 'dashboard/account/credit/limit/review/',
      dashboard: '/dashboard/account/detail/'
   };
}
