import { Constants } from '../app/core/utils/constants';
import * as data from './../assets/data.json';
import * as tokens from './../assets/tokens.json';

export const environment = {
   envName: Constants.environmentNames.etePilot,
   production: true,
   nedbankApiUrl: 'https://api-q.nedsecure.co.za/nedbank/nedbankid/',
   logApiUrl: 'http://dvnpknmapiweb01:4321/',
   apiUrl: 'https://api-q.nedsecure.co.za/nedbank/',
   signalRUrl: 'https://dcchat-e.nedsecure.co.za/signalr/hubs',
   downloadStatementUrl: 'https://q-ecs.nedbank.co.za/',
   cardImageUrl: 'https://q-nedmoncontent.nedbank.co.za/assets/png/card-images/',
   password: 'adminqa',
   logoutOnRefresh: true,
   rapportSetting: {
      popup: true,
      showcount: 4,
      popupdurationms: 60000
   },
   session: {
      idleTime: 60,
      timeOutWarning: 180
   },
   features: {
      dashboard: true,
      payment: true,
      transfer: true,
      buy: true,
      cards: true,
      instantPayment: true,
      settings: true,
      buyElectricity: true,
      branchlocator: true,
      game: true,
      feedback: true,
      pppEnrolment: true,
      forgotDetails: true,
      crossBorderPayment: false,
      lottoPallet: true,
      upliftDormancy: true,
      cardFreeze: true,
      accountsShowHideFeature: true,
      cardContactless: true,
      cardInternetPurchases: true,
      rewardsFeature: true,
      greenbackEnrolment: true,
      redemption: true,
      chargesAndFeeToggle: false,
      balanceDetail: true,
      transactionDetail: true,
      maintainOverdraft: true,
      accountRename: true,
      accountShare: true,
      travelCardAccount: true,
      travelCardManagement: true,
      travelCardTrips: true,
      travelCardPriority: true,
      settlement: true,
      chat: true,
      requestBuildingLoanPayment: true,
      reportSuspicious: true,
      statementPreferences: true,
      statementsDocuments: true,
      plHlStatementsDocument: true,
      activateCreditCard: true,
      stopDebitOrder: true,
      cancelStopOrder: true,
      garageCardInternetPurchase: true,
      settlementMfc: true,
      viewBanker: true,
      loanPaymentDetails: true,
      mfcPaymentDetails: true,
      mfcUpdatePaymentDetails: true,
      noticeOfWithdrawal: true,
      annualCreditReview: true,
      statementPreferencesMFC: true,
      transactionSearch: true,
      garageCardAtmLimits: true,
      settlementHl: true,
      overseasTravelNotification: true,
      automaticPaymentOrder: true,
      trusteer: true,
      requestCreditLimitIncrease: true,
      openNewAccount: true,
      manageLoan: true,
      it3bDocuments: true,
      statementsCASA: true,
      preApprovedOffers: false,
   },
   audience: 'https://newmoneyweb/',
   headers: tokens['tokens'],
   googleMapApiKey: 'AIzaSyCn3nYFFV9US6jl6yT0Bqk70oAuj9WiwII',
   gaTrackingId: ''
};
