export interface ICountry {
   code: string;
   name: string;
}

export class CountryList {

   public static items: ICountry[] = [
      { name: 'ANDORRA', code: 'AD' },
      { name: 'UNITED ARAB EMIRATES', code: 'AE' },
      { name: 'AFGHANISTAN', code: 'AF' },
      { name: 'ANTIGUA AND BARBUDA', code: 'AG' },
      { name: 'ANGUILLA', code: 'AI' },
      { name: 'ALBANIA', code: 'AL' },
      { name: 'ARMENIA', code: 'AM' },
      { name: 'ANGOLA', code: 'AO' },
      { name: 'ANTARCTICA', code: 'AQ' },
      { name: 'ARGENTINA', code: 'AR' },
      { name: 'AMERICAN SAMOA', code: 'AS' },
      { name: 'AUSTRIA', code: 'AT' },
      { name: 'AUSTRALIA', code: 'AU' },
      { name: 'ARUBA', code: 'AW' },
      { name: 'ALAND ISLANDS', code: 'AX' },
      { name: 'AZERBAIJAN', code: 'AZ' },
      { name: 'BOSNIA AND HERZEGOWINA', code: 'BA' },
      { name: 'BARBADOS', code: 'BB' },
      { name: 'BANGLADESH', code: 'BD' },
      { name: 'BELGIUM', code: 'BE' },
      { name: 'BURKINA FASO', code: 'BF' },
      { name: 'BULGARIA', code: 'BG' },
      { name: 'BAHRAIN', code: 'BH' },
      { name: 'BURUNDI', code: 'BI' },
      { name: 'BENIN', code: 'BJ' },
      { name: 'SAINT BARTHELEMY', code: 'BL' },
      { name: 'BERMUDA', code: 'BM' },
      { name: 'BRUNEI DARUSSALAM', code: 'BN' },
      { name: 'BOLIVIA, PLURINATIONAL STATE OF', code: 'BO' },
      { name: 'BONAIRE, SAINT EUSATIUS AND SABA', code: 'BQ' },
      { name: 'BRAZIL', code: 'BR' },
      { name: 'BAHAMAS', code: 'BS' },
      { name: 'BHUTAN', code: 'BT' },
      { name: 'BOUVET ISLAND', code: 'BV' },
      { name: 'BOTSWANA', code: 'BW' },
      { name: 'BELARUS', code: 'BY' },
      { name: 'BELIZE', code: 'BZ' },
      { name: 'CANADA', code: 'CA' },
      { name: 'COCOS (KEELING) ISLANDS', code: 'CC' },
      { name: 'CONGO, THE DEMOCRATIC REPUBLIC OF', code: 'CD' },
      { name: 'CENTRAL AFRICAN REPUBLIC', code: 'CF' },
      { name: 'CONGO', code: 'CG' },
      { name: 'SWITZERLAND', code: 'CH' },
      { name: 'COTE D\'IVOIRE', code: 'CI' },
      { name: 'COOK ISLANDS', code: 'CK' },
      { name: 'CHILE', code: 'CL' },
      { name: 'CAMEROON', code: 'CM' },
      { name: 'CHINA', code: 'CN' },
      { name: 'COLOMBIA', code: 'CO' },
      { name: 'COSTA RICA', code: 'CR' },
      { name: 'SIBERIA AND MONTENEGRO', code: 'CS' },
      { name: 'CUBA', code: 'CU' },
      { name: 'CAPE VERDE', code: 'CV' },
      { name: 'CURACAO', code: 'CW' },
      { name: 'CHRISTMAS ISLAND', code: 'CX' },
      { name: 'CYPRUS', code: 'CY' },
      { name: 'CZECH REPUBLIC', code: 'CZ' },
      { name: 'GERMANY', code: 'DE' },
      { name: 'DJIBOUTI', code: 'DJ' },
      { name: 'DENMARK', code: 'DK' },
      { name: 'DOMINICA', code: 'DM' },
      { name: 'DOMINICAN REPUBLIC', code: 'DO' },
      { name: 'ALGERIA', code: 'DZ' },
      { name: 'ECUADOR', code: 'EC' },
      { name: 'ESTONIA', code: 'EE' },
      { name: 'EGYPT', code: 'EG' },
      { name: 'WESTERN SAHARA', code: 'EH' },
      { name: 'ERITREA', code: 'ER' },
      { name: 'SPAIN', code: 'ES' },
      { name: 'ETHIOPIA', code: 'ET' },
      { name: 'FINLAND', code: 'FI' },
      { name: 'FIJI', code: 'FJ' },
      { name: 'FALKLAND ISLANDS (MALVINAS)', code: 'FK' },
      { name: 'MICRONESIA, FEDERATED STATES OF', code: 'FM' },
      { name: 'FAROE ISLANDS', code: 'FO' },
      { name: 'FRANCE', code: 'FR' },
      { name: 'GABON', code: 'GA' },
      { name: 'UNITED KINGDOM', code: 'GB' },
      { name: 'GRENADA', code: 'GD' },
      { name: 'GEORGIA', code: 'GE' },
      { name: 'FRENCH GUIANA', code: 'GF' },
      { name: 'GUERNSEY', code: 'GG' },
      { name: 'GHANA', code: 'GH' },
      { name: 'GIBRALTAR', code: 'GI' },
      { name: 'GREENLAND', code: 'GL' },
      { name: 'GAMBIA', code: 'GM' },
      { name: 'GUINEA', code: 'GN' },
      { name: 'GUADELOUPE', code: 'GP' },
      { name: 'EQUATORIAL GUINEA', code: 'GQ' },
      { name: 'GREECE', code: 'GR' },
      { name: 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISL', code: 'GS' },
      { name: 'GUATEMALA', code: 'GT' },
      { name: 'GUAM', code: 'GU' },
      { name: 'GUINEA-BISSAU', code: 'GW' },
      { name: 'GUYANA', code: 'GY' },
      { name: 'HONG KONG', code: 'HK' },
      { name: 'HEARD ISLAND AND MCDONALD ISLANDS', code: 'HM' },
      { name: 'HONDURAS', code: 'HN' },
      { name: 'CROATIA', code: 'HR' },
      { name: 'HAITI', code: 'HT' },
      { name: 'HUNGARY', code: 'HU' },
      { name: 'INDONESIA', code: 'ID' },
      { name: 'IRELAND', code: 'IE' },
      { name: 'ISRAEL', code: 'IL' },
      { name: 'ISLE OF MAN', code: 'IM' },
      { name: 'INDIA', code: 'IN' },
      { name: 'BRITISH INDIAN OCEAN TERRITORY', code: 'IO' },
      { name: 'IRAQ', code: 'IQ' },
      { name: 'IRAN, ISLAMIC REPUBLIC OF', code: 'IR' },
      { name: 'ICELAND', code: 'IS' },
      { name: 'ITALY', code: 'IT' },
      { name: 'JERSEY', code: 'JE' },
      { name: 'JAMAICA', code: 'JM' },
      { name: 'JORDAN', code: 'JO' },
      { name: 'JAPAN', code: 'JP' },
      { name: 'KENYA', code: 'KE' },
      { name: 'KYRGYZSTAN', code: 'KG' },
      { name: 'CAMBODIA', code: 'KH' },
      { name: 'KIRIBATI', code: 'KI' },
      { name: 'COMOROS', code: 'KM' },
      { name: 'SAINT KITTS AND NEVIS', code: 'KN' },
      { name: 'KOREA, DEMOCRATIC PEOPLE\'S REPUBLIC OF', code: 'KP' },
      { name: 'KOREA (REPUBLIC OF)', code: 'KR' },
      { name: 'KUWAIT', code: 'KW' },
      { name: 'CAYMAN ISLANDS', code: 'KY' },
      { name: 'KAZAKHSTAN', code: 'KZ' },
      { name: 'LAO PEOPLE\'S DEMOCRATIC REPUBLIC', code: 'LA' },
      { name: 'LEBANON', code: 'LB' },
      { name: 'SAINT LUCIA', code: 'LC' },
      { name: 'LIECHTENSTEIN', code: 'LI' },
      { name: 'SRI LANKA', code: 'LK' },
      { name: 'LIBERIA', code: 'LR' },
      { name: 'LESOTHO', code: 'LS' },
      { name: 'LITHUANIA', code: 'LT' },
      { name: 'LUXEMBOURG', code: 'LU' },
      { name: 'LATVIA', code: 'LV' },
      { name: 'LIBYAN ARAB JAMAHIRIYA', code: 'LY' },
      { name: 'MOROCCO', code: 'MA' },
      { name: 'MONACO', code: 'MC' },
      { name: 'MOLDOVA', code: 'MD' },
      { name: 'MONTENEGRO', code: 'ME' },
      { name: 'SAINT-MARTIN', code: 'MF' },
      { name: 'MADAGASCAR', code: 'MG' },
      { name: 'MARSHALL ISLANDS', code: 'MH' },
      { name: 'MACEDONIA', code: 'MK' },
      { name: 'MALI', code: 'ML' },
      { name: 'MYANMAR', code: 'MM' },
      { name: 'MONGOLIA', code: 'MN' },
      { name: 'MACAO', code: 'MO' },
      { name: 'NORTHERN MARIANA ISLANDS', code: 'MP' },
      { name: 'MARTINIQUE', code: 'MQ' },
      { name: 'MAURITANIA', code: 'MR' },
      { name: 'MONTSERRAT', code: 'MS' },
      { name: 'MALTA', code: 'MT' },
      { name: 'MAURITIUS', code: 'MU' },
      { name: 'MALDIVES', code: 'MV' },
      { name: 'MALAWI', code: 'MW' },
      { name: 'MEXICO', code: 'MX' },
      { name: 'MALAYSIA', code: 'MY' },
      { name: 'MOZAMBIQUE', code: 'MZ' },
      { name: 'NAMIBIA', code: 'NA' },
      { name: 'NEW CALEDONIA', code: 'NC' },
      { name: 'NIGER', code: 'NE' },
      { name: 'NORFOLK ISLAND', code: 'NF' },
      { name: 'NIGERIA', code: 'NG' },
      { name: 'NICARAGUA', code: 'NI' },
      { name: 'NETHERLANDS', code: 'NL' },
      { name: 'NORWAY', code: 'NO' },
      { name: 'NEPAL', code: 'NP' },
      { name: 'NAURU', code: 'NR' },
      { name: 'NIUE', code: 'NU' },
      { name: 'NEW ZEALAND', code: 'NZ' },
      { name: 'OMAN', code: 'OM' },
      { name: 'PANAMA', code: 'PA' },
      { name: 'PERU', code: 'PE' },
      { name: 'FRENCH POLYNESIA', code: 'PF' },
      { name: 'INDEPENDENT STATE OF PAPUA NEW GUINEA', code: 'PG' },
      { name: 'PHILIPPINES', code: 'PH' },
      { name: 'PAKISTAN', code: 'PK' },
      { name: 'POLAND', code: 'PL' },
      { name: 'SAINT PIERRE AND MIQUELON', code: 'PM' },
      { name: 'PITCAIRN', code: 'PN' },
      { name: 'PUERTO RICO', code: 'PR' },
      { name: 'PALESTINIAN STATE OF', code: 'PS' },
      { name: 'PORTUGAL', code: 'PT' },
      { name: 'PALAU', code: 'PW' },
      { name: 'PARAGUAY', code: 'PY' },
      { name: 'QATAR', code: 'QA' },
      { name: 'REUNION', code: 'RE' },
      { name: 'ROMANIA', code: 'RO' },
      { name: 'SERBIA', code: 'RS' },
      { name: 'RUSSIAN FEDERATION', code: 'RU' },
      { name: 'RWANDA', code: 'RW' },
      { name: 'SAUDI ARABIA', code: 'SA' },
      { name: 'SOLOMON ISLANDS', code: 'SB' },
      { name: 'SEYCHELLES', code: 'SC' },
      { name: 'SUDAN', code: 'SD' },
      { name: 'SWEDEN', code: 'SE' },
      { name: 'SINGAPORE', code: 'SG' },
      { name: 'ST.HELENA,ASCENSION AND TRISTAN DA CUNHA', code: 'SH' },
      { name: 'SLOVENIA', code: 'SI' },
      { name: 'SVALBARD AND JAN MAYEN', code: 'SJ' },
      { name: 'SLOVAKIA', code: 'SK' },
      { name: 'SIERRA LEONE', code: 'SL' },
      { name: 'SAN MARINO', code: 'SM' },
      { name: 'SENEGAL', code: 'SN' },
      { name: 'FEDERAL REPUBLIC OF SOMALIA', code: 'SO' },
      { name: 'SURINAME', code: 'SR' },
      { name: 'SOUTH SUDAN', code: 'SS' },
      { name: 'SAO TOME AND PRINCIPE', code: 'ST' },
      { name: 'EL SALVADOR', code: 'SV' },
      { name: 'SINT MAARTEN (DUTCH)', code: 'SX' },
      { name: 'SYRIAN ARAB REPUBLIC', code: 'SY' },
      { name: 'SWAZILAND', code: 'SZ' },
      { name: 'TURKS AND CAICOS ISLANDS', code: 'TC' },
      { name: 'CHAD', code: 'TD' },
      { name: 'FRENCH SOUTHERN TERRITORIES', code: 'TF' },
      { name: 'TOGO', code: 'TG' },
      { name: 'THAILAND', code: 'TH' },
      { name: 'TAJIKISTAN', code: 'TJ' },
      { name: 'TOKELAU', code: 'TK' },
      { name: 'TIMOR-LESTE', code: 'TL' },
      { name: 'TURKMENISTAN', code: 'TM' },
      { name: 'TUNISIA', code: 'TN' },
      { name: 'TONGA', code: 'TO' },
      { name: 'TURKEY', code: 'TR' },
      { name: 'TRINIDAD AND TOBAGO', code: 'TT' },
      { name: 'TUVALU', code: 'TV' },
      { name: 'TAIWAN, PROVINCE OF CHINA', code: 'TW' },
      { name: 'TANZANIA, UNITED REPUBLIC OF', code: 'TZ' },
      { name: 'UKRAINE', code: 'UA' },
      { name: 'UGANDA', code: 'UG' },
      { name: 'UNITED STATES MINOR OUTLYING ISLANDS', code: 'UM' },
      { name: 'UNITED STATES', code: 'US' },
      { name: 'URUGUAY', code: 'UY' },
      { name: 'UZBEKISTAN', code: 'UZ' },
      { name: 'VATICAN CITY STATE (HOLY CITY)', code: 'VA' },
      { name: 'SAINT VINCENT AND THE GRENADINES', code: 'VC' },
      { name: 'VENEZUELA, BOLIVARIAN REPUBLIC OF', code: 'VE' },
      { name: 'VIRGIN ISLANDS (BRITISH)', code: 'VG' },
      { name: 'VIRGIN ISLANDS (US)', code: 'VI' },
      { name: 'VIETNAM', code: 'VN' },
      { name: 'VANUATU', code: 'VU' },
      { name: 'WALLIS AND FUTUNA', code: 'WF' },
      { name: 'SAMOA', code: 'WS' },
      { name: 'YEMEN', code: 'YE' },
      { name: 'MAYOTTE', code: 'YT' },
      { name: 'YUGSOLIVA', code: 'YU' },
      { name: 'ZAMBIA', code: 'ZM' },
      { name: 'ZIMBABWE', code: 'ZW' }
   ];
}
